/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import thread.AutoSync;

/**
 *
 * @author trana
 */
public class mainForm extends javax.swing.JFrame {

    /**
     * Creates new form mainForm
     */
    private String event = "";
    private String eventID = "";

    Thread auto = new Thread(new AutoSync(this));

    public mainForm() {
        initComponents();

        resetBody();
        dashboard2.setVisible(true);
        Color clr = new Color(204, 204, 255);
        DashBoard.setBackground(clr);
        chooseEvent1.setMF(this);
        dashboard2.setMF(this);

//        auto.run();
    }

    public void setEvent(String event, String eventID) {
        this.event = event;
        this.eventID = eventID;
        evenName.setText(event);
    }

    public String GetEventID() {
        return this.eventID = eventID;
    }

    private void resetButtonColor() {
        Color clr = new Color(0, 153, 255);
        DashBoard.setBackground(clr);
        Attendance.setBackground(clr);
        chooseEvent.setBackground(clr);
        Sync.setBackground(clr);
        navbar.repaint();
    }

    private void resetBody() {
        attendance1.setVisible(false);
        chooseEvent1.setVisible(false);
        dashboard2.setVisible(false);
        sync1.setVisible(false);
    }

    public void changeUIToAttendance() {
        if (event != "") {
            resetButtonColor();
            Color clr = new Color(204, 204, 255);
            Attendance.setBackground(clr);
            resetBody();
            attendance1.setVisible(true);
        } else {
            resetButtonColor();
            Color clr = new Color(204, 204, 255);
            chooseEvent.setBackground(clr);
            resetBody();
            chooseEvent1.loadData();
            chooseEvent1.setVisible(true);
        }
    }

    public void changeUIToSync() {
        resetButtonColor();
        Color clr = new Color(204, 204, 255);
        Sync.setBackground(clr);
        resetBody();
        sync1.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbar = new javax.swing.JPanel();
        DashBoard = new javax.swing.JButton();
        Attendance = new javax.swing.JButton();
        chooseEvent = new javax.swing.JButton();
        Sync = new javax.swing.JButton();
        Status = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        syncStatus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        evenName = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        attendance1 = new GUI.attendance();
        dashboard2 = new GUI.dashboard();
        chooseEvent1 = new GUI.chooseEvent();
        sync1 = new GUI.sync();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Diem Danh");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(480, 320));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        navbar.setBackground(new java.awt.Color(0, 153, 255));
        navbar.setMaximumSize(new java.awt.Dimension(50, 320));
        navbar.setMinimumSize(new java.awt.Dimension(50, 320));

        DashBoard.setBackground(new java.awt.Color(0, 153, 255));
        DashBoard.setIcon(new javax.swing.ImageIcon("C:\\Users\\trana\\Pictures\\New folder (2)\\dashboard.png")); // NOI18N
        DashBoard.setMaximumSize(new java.awt.Dimension(50, 50));
        DashBoard.setMinimumSize(new java.awt.Dimension(50, 50));
        DashBoard.setPreferredSize(new java.awt.Dimension(50, 50));
        DashBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashBoardActionPerformed(evt);
            }
        });

        Attendance.setBackground(new java.awt.Color(0, 153, 255));
        Attendance.setIcon(new javax.swing.ImageIcon("C:\\Users\\trana\\Pictures\\New folder (2)\\125544-32.png")); // NOI18N
        Attendance.setToolTipText("");
        Attendance.setMaximumSize(new java.awt.Dimension(50, 50));
        Attendance.setMinimumSize(new java.awt.Dimension(50, 50));
        Attendance.setPreferredSize(new java.awt.Dimension(50, 50));
        Attendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttendanceActionPerformed(evt);
            }
        });

        chooseEvent.setBackground(new java.awt.Color(0, 153, 255));
        chooseEvent.setIcon(new javax.swing.ImageIcon("C:\\Users\\trana\\Pictures\\New folder (2)\\event.png")); // NOI18N
        chooseEvent.setMaximumSize(new java.awt.Dimension(50, 50));
        chooseEvent.setMinimumSize(new java.awt.Dimension(50, 50));
        chooseEvent.setPreferredSize(new java.awt.Dimension(50, 50));
        chooseEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseEventActionPerformed(evt);
            }
        });

        Sync.setBackground(new java.awt.Color(0, 153, 255));
        Sync.setIcon(new javax.swing.ImageIcon("C:\\Users\\trana\\Pictures\\New folder (2)\\sync-arrows.png")); // NOI18N
        Sync.setMaximumSize(new java.awt.Dimension(50, 50));
        Sync.setMinimumSize(new java.awt.Dimension(50, 50));
        Sync.setPreferredSize(new java.awt.Dimension(50, 50));
        Sync.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SyncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DashBoard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Attendance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseEvent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sync, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addComponent(DashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Attendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chooseEvent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sync, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Status.setBackground(new java.awt.Color(255, 255, 255));
        Status.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Sync:");

        syncStatus.setText("none");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Event:");

        evenName.setText("No Event");
        evenName.setToolTipText("");

        javax.swing.GroupLayout StatusLayout = new javax.swing.GroupLayout(Status);
        Status.setLayout(StatusLayout);
        StatusLayout.setHorizontalGroup(
            StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StatusLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(evenName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(syncStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        StatusLayout.setVerticalGroup(
            StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(syncStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2)
                .addComponent(evenName))
        );

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        body.add(attendance1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 290));
        body.add(dashboard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        body.add(chooseEvent1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        body.add(sync1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DashBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashBoardActionPerformed
        resetButtonColor();
        Color clr = new Color(204, 204, 255);
        DashBoard.setBackground(clr);
        resetBody();
        dashboard2.setVisible(true);
    }//GEN-LAST:event_DashBoardActionPerformed

    private void AttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttendanceActionPerformed
        changeUIToAttendance();
    }//GEN-LAST:event_AttendanceActionPerformed

    private void chooseEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseEventActionPerformed
        resetButtonColor();
        Color clr = new Color(204, 204, 255);
        chooseEvent.setBackground(clr);
        resetBody();
        chooseEvent1.loadData();
        chooseEvent1.setVisible(true);
    }//GEN-LAST:event_chooseEventActionPerformed

    private void SyncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SyncActionPerformed
        changeUIToSync();
    }//GEN-LAST:event_SyncActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        module.Database db = new module.Database();
        db.update("UPDATE `setting` SET `value` = '' WHERE `id` = 1");
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Attendance;
    private javax.swing.JButton DashBoard;
    private javax.swing.JPanel Status;
    private javax.swing.JButton Sync;
    private GUI.attendance attendance1;
    private javax.swing.JPanel body;
    private javax.swing.JButton chooseEvent;
    private GUI.chooseEvent chooseEvent1;
    private GUI.dashboard dashboard2;
    private javax.swing.JLabel evenName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel navbar;
    private GUI.sync sync1;
    private javax.swing.JLabel syncStatus;
    // End of variables declaration//GEN-END:variables
}
